import { Lpk } from "./types";

export const mockLpkData: Lpk[] = [
  {
    name: "LPK FUJIYAMA GLOBAL INDONESIA",
    province: "JAWA TENGAH",
    vin: "1810337203",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 165 },
      { year: 2023, count: 183 },
      { year: 2024, count: 173 },
      { year: 2025, count: 138 },
    ],
    placement: 0,
  },
  {
    name: "LPK JOGJA KENSHU SENTA",
    province: "DI YOGYAKARTA",
    vin: "1809340101",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 51 },
      { year: 2023, count: 103 },
      { year: 2024, count: 78 },
      { year: 2025, count: 61 },
    ],
    placement: 0,
  },
  {
    name: "LPK HIRO",
    province: "JAWA TENGAH",
    vin: "1810331301",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 443 },
      { year: 2023, count: 563 },
      { year: 2024, count: 365 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK SERBAINDO",
    province: "JAWA TENGAH",
    vin: "1906337301",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "unverified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 0 },
      { year: 2023, count: 66 },
      { year: 2024, count: 101 },
      { year: 2025, count: 158 },
    ],
    placement: 0,
  },
  {
    name: "LPK AQNESIA GLOBAL SOLO",
    province: "-",
    vin: "2211337202",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "unverified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 0 },
      { year: 2023, count: 23 },
      { year: 2024, count: 60 },
      { year: 2025, count: 94 },
    ],
    placement: 0,
  },
  {
    name: "LPKS MAGDY INDONESIA",
    province: "JAWA TENGAH",
    vin: "1809332205",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 35 },
      { year: 2023, count: 7 },
      { year: 2024, count: 0 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK IWA KYO INDONESIA",
    province: "JAWA TENGAH",
    vin: "1912337201",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "unverified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 5 },
      { year: 2023, count: 22 },
      { year: 2024, count: 32 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK YUTAKA MITRA INDONESIA",
    province: "JAWA TENGAH",
    vin: "1907337401",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "unverified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 220 },
      { year: 2023, count: 193 },
      { year: 2024, count: 152 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK PROGRES INTI SOLUSI",
    province: "JAWA TENGAH",
    vin: "2204331001",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "unverified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 0 },
      { year: 2023, count: 20 },
      { year: 2024, count: 37 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK SO BHASKORO TRAINING & EDUCATION CENTRE",
    province: "-",
    vin: "1810331106",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 25 },
      { year: 2023, count: 11 },
      { year: 2024, count: 8 },
      { year: 2025, count: 22 },
    ],
    placement: 0,
  },
  {
    name: "LPK SO OETOMO DIKLAT MAGANG JEPANG",
    province: "-",
    vin: "1810331102",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 15 },
      { year: 2023, count: 11 },
      { year: 2024, count: 11 },
      { year: 2025, count: 9 },
    ],
    placement: 0,
  },
  {
    name: "LPK CAHAYA MANDIRI INDONESIA",
    province: "-",
    vin: "1809331301",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 240 },
      { year: 2023, count: 196 },
      { year: 2024, count: 155 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK JINZIYA KLATEN INDONESIA",
    province: "JAWA TENGAH",
    vin: "Belum Ada",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "unverified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 0 },
      { year: 2023, count: 8 },
      { year: 2024, count: 21 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK BINTANG DARMA INTAMA ( BDI )",
    province: "-",
    vin: "1810337202",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 136 },
      { year: 2023, count: 154 },
      { year: 2024, count: 105 },
      { year: 2025, count: 120 },
    ],
    placement: 0,
  },
  {
    name: "LPK HOMARE ACADEMY",
    province: "-",
    vin: "2012330901",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "unverified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 72 },
      { year: 2023, count: 175 },
      { year: 2024, count: 139 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK MARTANI",
    province: "JAWA TENGAH",
    vin: "1810332211",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 105 },
      { year: 2023, count: 173 },
      { year: 2024, count: 193 },
      { year: 2025, count: 124 },
    ],
    placement: 0,
  },
  {
    name: "LPK GLOBALINDO",
    province: "-",
    vin: "1810340404",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 157 },
      { year: 2023, count: 176 },
      { year: 2024, count: 76 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK GLOBAL ALPHA",
    province: "JAWA TENGAH",
    vin: "1911331102",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 114 },
      { year: 2023, count: 106 },
      { year: 2024, count: 112 },
      { year: 2025, count: 86 },
    ],
    placement: 0,
  },
  {
    name: "HIGLOB",
    province: "-",
    vin: "1911340401",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 282 },
      { year: 2023, count: 735 },
      { year: 2024, count: 354 },
      { year: 2025, count: 283 },
    ],
    placement: 0,
  },
  {
    name: "Lpk aoisora sinar indonesia",
    province: "JAWA TENGAH",
    vin: "1911337201",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 137 },
      { year: 2023, count: 123 },
      { year: 2024, count: 91 },
      { year: 2025, count: 131 },
    ],
    placement: 0,
  },
  {
    name: "LPK WAKAWASHI MANDIRI INDONESIA",
    province: "-",
    vin: "1810340403",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 57 },
      { year: 2023, count: 65 },
      { year: 2024, count: 100 },
      { year: 2025, count: 47 },
    ],
    placement: 0,
  },
  {
    name: "LPK BHUMI IKA NUSWANTARA",
    province: "JAWA TENGAH",
    vin: "1809332206",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 120 },
      { year: 2023, count: 142 },
      { year: 2024, count: 106 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK Mitra Jaya Indonesia",
    province: "JAWA TENGAH",
    vin: "2207337101",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 142 },
      { year: 2023, count: 130 },
      { year: 2024, count: 109 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "Uchumaru",
    province: "-",
    vin: "1810340201",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 21 },
      { year: 2023, count: 38 },
      { year: 2024, count: 36 },
      { year: 2025, count: 22 },
    ],
    placement: 0,
  },
  {
    name: "LPK Kizuna Mitra Indonesia",
    province: "JAWA TENGAH",
    vin: "1810351504",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "unverified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 32 },
      { year: 2023, count: 53 },
      { year: 2024, count: 33 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK. AISHIRO GAKUEN",
    province: "JAWA TENGAH",
    vin: "1809332201",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 4 },
      { year: 2023, count: 48 },
      { year: 2024, count: 67 },
      { year: 2025, count: 44 },
    ],
    placement: 0,
  },
  {
    name: "LPK SO Shiawase Lestari Indonesia",
    province: "-",
    vin: "2012332203",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "unverified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 0 },
      { year: 2023, count: 14 },
      { year: 2024, count: 0 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK BAHTERA MITRA UNGGULAN",
    province: "JAWA TENGAH",
    vin: "211321301",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "unverified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 0 },
      { year: 2023, count: 12 },
      { year: 2024, count: 20 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK WAKASHIO GAKKOU",
    province: "JAWA TENGAH",
    vin: "1810332505",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 30 },
      { year: 2023, count: 44 },
      { year: 2024, count: 52 },
      { year: 2025, count: 30 },
    ],
    placement: 0,
  },
  {
    name: "LPK BALI NIRWANA SPA SCHOOL INTERNATIONAL",
    province: "-",
    vin: "2112510301",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 42 },
      { year: 2023, count: 42 },
      { year: 2024, count: 44 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK MULIA MEISOU INDONESIA",
    province: "JAWA BARAT",
    vin: "2206327301",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 256 },
      { year: 2023, count: 334 },
      { year: 2024, count: 135 },
      { year: 2025, count: 136 },
    ],
    placement: 0,
  },
  {
    name: "LPK SAKURA INDONESIA",
    province: "LAMPUNG",
    vin: "2006180302",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 410 },
      { year: 2023, count: 232 },
      { year: 2024, count: 114 },
      { year: 2025, count: 117 },
    ],
    placement: 0,
  },
  {
    name: "LPK PT. REJEKI LANGGENG MAKMUR",
    province: "BANTEN",
    vin: "2103367101",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 14 },
      { year: 2023, count: 12 },
      { year: 2024, count: 12 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK PT JIAEC",
    province: "-",
    vin: "2107327061",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 979 },
      { year: 2023, count: 1.061 },
      { year: 2024, count: 949 },
      { year: 2025, count: 756 },
    ],
    placement: 0,
  },
  {
    name: "LPK MULIA MANDIRI INDONESIA",
    province: "-",
    vin: "2009320401",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 447 },
      { year: 2023, count: 508 },
      { year: 2024, count: 519 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK YUMNAA ARSY KARA",
    province: "-",
    vin: "1907327302",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "unverified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 36 },
      { year: 2023, count: 16 },
      { year: 2024, count: 45 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK MEGUMI",
    province: "DI YOGYAKARTA",
    vin: "1810340209",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 379 },
      { year: 2023, count: 395 },
      { year: 2024, count: 306 },
      { year: 2025, count: 219 },
    ],
    placement: 0,
  },
  {
    name: "LPK MIRAI NUSANTARA",
    province: "JAWA BARAT",
    vin: "2002320409",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 288 },
      { year: 2023, count: 267 },
      { year: 2024, count: 251 },
      { year: 2025, count: 169 },
    ],
    placement: 0,
  },
  {
    name: "LPK YUUKI SHORAI INDONESIA",
    province: "JAWA BARAT",
    vin: "2111321601",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 107 },
      { year: 2023, count: 89 },
      { year: 2024, count: 42 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK YAYASAN SUNDAGAIYA",
    province: "JAWA BARAT",
    vin: "1810320402",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 356 },
      { year: 2023, count: 358 },
      { year: 2024, count: 391 },
      { year: 2025, count: 121 },
    ],
    placement: 0,
  },
  {
    name: "LPK COOP INDONESIA",
    province: "-",
    vin: "1903321102",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 495 },
      { year: 2023, count: 764 },
      { year: 2024, count: 567 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK REKADAYA KARSA UTAMA",
    province: "JAWA TIMUR",
    vin: "2006351502",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 66 },
      { year: 2023, count: 56 },
      { year: 2024, count: 60 },
      { year: 2025, count: 63 },
    ],
    placement: 0,
  },
  {
    name: "LPK PERWITA NUSARAYA",
    province: "JAWA TIMUR",
    vin: "1810351503",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "unverified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 0 },
      { year: 2023, count: 8 },
      { year: 2024, count: 32 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK MITRA SARANA SEJAHTERA",
    province: "JAWA TIMUR",
    vin: "357320602",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 30 },
      { year: 2023, count: 222 },
      { year: 2024, count: 735 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK ASA COURSE INDONESIA",
    province: "JAWA TENGAH",
    vin: "2103331002",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 184 },
      { year: 2023, count: 186 },
      { year: 2024, count: 155 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK BISTRA KENSHU SENTA",
    province: "BALI",
    vin: "1810510101",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 7 },
      { year: 2023, count: 67 },
      { year: 2024, count: 105 },
      { year: 2025, count: 75 },
    ],
    placement: 0,
  },
  {
    name: "LPK NAKAYOSHI GAKUIN CENTER",
    province: "JAWA BARAT",
    vin: "1810321005",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 145 },
      { year: 2023, count: 450 },
      { year: 2024, count: 688 },
      { year: 2025, count: 628 },
    ],
    placement: 0,
  },
  {
    name: "LPK SINAR TERANG BERSATU",
    province: "BALI",
    vin: "1907517101",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "unverified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 56 },
      { year: 2023, count: 77 },
      { year: 2024, count: 53 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK EIKOU KAKEHASHI Indonesia",
    province: "JAWA BARAT",
    vin: "2210320401",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "unverified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 75 },
      { year: 2023, count: 75 },
      { year: 2024, count: 75 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK EDUCATION JAPAN CENTER INDONESIA",
    province: "JAWA BARAT",
    vin: "2003321721",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 60 },
      { year: 2023, count: 60 },
      { year: 2024, count: 102 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK AUDI PRATAMA MANDIRI INDONESIA",
    province: "JAWA BARAT",
    vin: "1809321101",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 123 },
      { year: 2023, count: 191 },
      { year: 2024, count: 115 },
      { year: 2025, count: 73 },
    ],
    placement: 0,
  },
  {
    name: "LPK KOCHI MAKMUR INDONESIA",
    province: "JAWA BARAT",
    vin: "1905320302",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 18 },
      { year: 2023, count: 49 },
      { year: 2024, count: 23 },
      { year: 2025, count: 40 },
    ],
    placement: 0,
  },
  {
    name: "LPK TRIMITRA MATAHARI MANDIRI",
    province: "JAWA BARAT",
    vin: "2207331201",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 370 },
      { year: 2023, count: 405 },
      { year: 2024, count: 453 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK WORLD TRAINING CENTER",
    province: "-",
    vin: "1904510701",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "unverified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 111 },
      { year: 2023, count: 345 },
      { year: 2024, count: 370 },
      { year: 2025, count: 123 },
    ],
    placement: 0,
  },
  {
    name: "LPK BANGKIT INDONESIA",
    province: "DKI JAKARTA",
    vin: "2207317401",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 462 },
      { year: 2023, count: 591 },
      { year: 2024, count: 408 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK LINTAS NEGERI",
    province: "BALI",
    vin: "2112510101",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 68 },
      { year: 2023, count: 96 },
      { year: 2024, count: 89 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPKS MAGDY INDONESIA",
    province: "JAWA TENGAH",
    vin: "2208337401",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 22 },
      { year: 2023, count: 3 },
      { year: 2024, count: 0 },
      { year: 2025, count: 5 },
    ],
    placement: 0,
  },
  {
    name: "LPK DUTA SAHAYA",
    province: "BALI",
    vin: "1810510201",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 308 },
      { year: 2023, count: 285 },
      { year: 2024, count: 222 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK KAIDOU GAKUIN",
    province: "JAWA BARAT",
    vin: "1809321601",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 95 },
      { year: 2023, count: 117 },
      { year: 2024, count: 167 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK MASAYUKI MITRA UTAMA",
    province: "JAWA BARAT",
    vin: "230532150",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "unverified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 0 },
      { year: 2023, count: 25 },
      { year: 2024, count: 30 },
      { year: 2025, count: 40 },
    ],
    placement: 0,
  },
  {
    name: "LPK JAPAN MANDIRI INDONESIA",
    province: "JAWA TENGAH",
    vin: "1912330905",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 44 },
      { year: 2023, count: 46 },
      { year: 2024, count: 48 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK ARCADIA",
    province: "JAWA TENGAH",
    vin: "1906330601",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 63 },
      { year: 2023, count: 109 },
      { year: 2024, count: 105 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK YASUI ABADI",
    province: "JAWA TENGAH",
    vin: "1912330301",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "unverified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 259 },
      { year: 2023, count: 292 },
      { year: 2024, count: 399 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK UNIVERSAL JAPAN COURSE",
    province: "-",
    vin: "1907332201'",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 516 },
      { year: 2023, count: 696 },
      { year: 2024, count: 405 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK KAGAYAKI TRAINING CENTRE BANDUNG",
    province: "JAWA BARAT",
    vin: "1910320405",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 65 },
      { year: 2023, count: 30 },
      { year: 2024, count: 50 },
      { year: 2025, count: 12 },
    ],
    placement: 0,
  },
  {
    name: "LPK PUSPA SETYA ABADI",
    province: "-",
    vin: "2009340401",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 4 },
      { year: 2023, count: 85 },
      { year: 2024, count: 119 },
      { year: 2025, count: 189 },
    ],
    placement: 0,
  },
  {
    name: "LPK JINZIYA KLATEN INDONESIA",
    province: "JAWA TENGAH",
    vin: "2004331005",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 0 },
      { year: 2023, count: 10 },
      { year: 2024, count: 16 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK ENTRUST LESTARI INDONESIA",
    province: "DKI JAKARTA",
    vin: "1810317203",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 0 },
      { year: 2023, count: 40 },
      { year: 2024, count: 20 },
      { year: 2025, count: 22 },
    ],
    placement: 0,
  },
  {
    name: "LPK PUDJI UTAMI",
    province: "JAWA BARAT",
    vin: "2301327601",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 0 },
      { year: 2023, count: 3 },
      { year: 2024, count: 2 },
      { year: 2025, count: 10 },
    ],
    placement: 0,
  },
  {
    name: "LPK NISHI JAWA JISSHU SENTA",
    province: "JAWA BARAT",
    vin: "1902320401",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "unverified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 85 },
      { year: 2023, count: 115 },
      { year: 2024, count: 107 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK JIEMA",
    province: "LAMPUNG",
    vin: "2004187201",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 116 },
      { year: 2023, count: 164 },
      { year: 2024, count: 213 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK OMOIYARI PERMATA INDONESIA",
    province: "JAWA TIMUR",
    vin: "2308352501",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "unverified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 0 },
      { year: 2023, count: 0 },
      { year: 2024, count: 42 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK ASTA KARYA",
    province: "DKI JAKARTA",
    vin: "317120083",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 92 },
      { year: 2023, count: 89 },
      { year: 2024, count: 127 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK BINA NUSANTARA SEJAHTERA",
    province: "-",
    vin: "1809350202",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 2 },
      { year: 2023, count: 14 },
      { year: 2024, count: 0 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK HIMAWARI",
    province: "-",
    vin: "1810350405",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 80 },
      { year: 2023, count: 131 },
      { year: 2024, count: 114 },
      { year: 2025, count: 29 },
    ],
    placement: 0,
  },
  {
    name: "LPK/SO KOMATSU TRAINING CENTER",
    province: "-",
    vin: "1908320401",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 0 },
      { year: 2023, count: 0 },
      { year: 2024, count: 0 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK KARUNIA DEWATA",
    province: "BALI",
    vin: "1810510302",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 113 },
      { year: 2023, count: 67 },
      { year: 2024, count: 80 },
      { year: 2025, count: 80 },
    ],
    placement: 0,
  },
  {
    name: "LPK PUSAKA MULIA INSANI",
    province: "JAWA TIMUR",
    vin: "351520644",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 0 },
      { year: 2023, count: 80 },
      { year: 2024, count: 264 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK LPJ BALI",
    province: "BALI",
    vin: "1810517102",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 108 },
      { year: 2023, count: 97 },
      { year: 2024, count: 90 },
      { year: 2025, count: 99 },
    ],
    placement: 0,
  },
  {
    name: "LPK MASSAIHARA",
    province: "JAWA BARAT",
    vin: "1810321606",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 149 },
      { year: 2023, count: 39 },
      { year: 2024, count: 115 },
      { year: 2025, count: 94 },
    ],
    placement: 0,
  },
  {
    name: "LPK HIKARI BALI",
    province: "BALI",
    vin: "2210510601",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "unverified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 0 },
      { year: 2023, count: 0 },
      { year: 2024, count: 43 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK JAPAN INDONESIA ASAORI",
    province: "BALI",
    vin: "1810510102",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 71 },
      { year: 2023, count: 47 },
      { year: 2024, count: 44 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK FAJAR INTERNASIONAL",
    province: "-",
    vin: "1811350701",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 86 },
      { year: 2023, count: 297 },
      { year: 2024, count: 182 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK MOMIJI",
    province: "JAWA TENGAH",
    vin: "2001330901",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 84 },
      { year: 2023, count: 80 },
      { year: 2024, count: 71 },
      { year: 2025, count: 87 },
    ],
    placement: 0,
  },
  {
    name: "SAKURA BINA CITA",
    province: "-",
    vin: "2008320101",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "unverified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 21 },
      { year: 2023, count: 9 },
      { year: 2024, count: 15 },
      { year: 2025, count: 48 },
    ],
    placement: 0,
  },
  {
    name: "LPK BALI GLOBAL ACADEMY",
    province: "-",
    vin: "2106510601",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 0 },
      { year: 2023, count: 54 },
      { year: 2024, count: 76 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK GLOBAL MANDIRI INDONESIA",
    province: "JAWA BARAT",
    vin: "2003321101",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 102 },
      { year: 2023, count: 165 },
      { year: 2024, count: 96 },
      { year: 2025, count: 89 },
    ],
    placement: 0,
  },
  {
    name: "PT LPK CAHAYA DUTA  BALI",
    province: "-",
    vin: "2303510104",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "unverified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 0 },
      { year: 2023, count: 0 },
      { year: 2024, count: 8 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK GANESHA KARYA ABADI",
    province: "-",
    vin: "1910517101",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 61 },
      { year: 2023, count: 81 },
      { year: 2024, count: 44 },
      { year: 2025, count: 29 },
    ],
    placement: 0,
  },
  {
    name: "LPK Darma",
    province: "-",
    vin: "1809517103",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 457 },
      { year: 2023, count: 390 },
      { year: 2024, count: 67 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK MAMORU GLOBAL PARTNERS",
    province: "-",
    vin: "2209321101",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 112 },
      { year: 2023, count: 22 },
      { year: 2024, count: 2 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK INDONESIA JAPAN MUSUBI",
    province: "JAWA BARAT",
    vin: "2009320404",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 35 },
      { year: 2023, count: 34 },
      { year: 2024, count: 62 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK CHUOO MANDIRI",
    province: "-",
    vin: "1809180901",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 23 },
      { year: 2023, count: 23 },
      { year: 2024, count: 18 },
      { year: 2025, count: 21 },
    ],
    placement: 0,
  },
  {
    name: "LPK ISMOYO JATI BERSINAR",
    province: "-",
    vin: "1907331001",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 0 },
      { year: 2023, count: 0 },
      { year: 2024, count: 0 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK SO PT MITRA BAHARI INDONESIA",
    province: "-",
    vin: "1911517101",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 43 },
      { year: 2023, count: 35 },
      { year: 2024, count: 49 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK PRIMA DUTA SEJATI",
    province: "JAWA TIMUR",
    vin: "1810357502",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 333 },
      { year: 2023, count: 549 },
      { year: 2024, count: 436 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK DAIMA AKADEMI NUSANTARA",
    province: "-",
    vin: "2409352402",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "unverified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 27 },
      { year: 2023, count: 34 },
      { year: 2024, count: 46 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK MANABU INSAN MULIA",
    province: "-",
    vin: "2106351503",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 0 },
      { year: 2023, count: 85 },
      { year: 2024, count: 134 },
      { year: 2025, count: 86 },
    ],
    placement: 0,
  },
  {
    name: "LPK MATAHARI PERDANA",
    province: "JAWA BARAT",
    vin: "2004327103",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 11 },
      { year: 2023, count: 47 },
      { year: 2024, count: 28 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK KANADE INDONESIA BERKAH",
    province: "JAWA TIMUR",
    vin: "2103351903",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 5 },
      { year: 2023, count: 19 },
      { year: 2024, count: 18 },
      { year: 2025, count: 32 },
    ],
    placement: 0,
  },
  {
    name: "LPK MAJESTA FOUNDATION INDONESIA",
    province: "-",
    vin: "1909330901",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 73 },
      { year: 2023, count: 72 },
      { year: 2024, count: 45 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK HARAPAN PUTERA BANDUNG INDONESIA",
    province: "JAWA BARAT",
    vin: "1910327305",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 180 },
      { year: 2023, count: 339 },
      { year: 2024, count: 284 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK JIRITSU NUSANTARA",
    province: "JAWA BARAT",
    vin: "2003327105",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 78 },
      { year: 2023, count: 70 },
      { year: 2024, count: 58 },
      { year: 2025, count: 51 },
    ],
    placement: 0,
  },
  {
    name: "LPK YAYASAN HINODE ABADI INDONESIA",
    province: "JAWA BARAT",
    vin: "2011327301",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 1 },
      { year: 2023, count: 46 },
      { year: 2024, count: 89 },
      { year: 2025, count: 98 },
    ],
    placement: 0,
  },
  {
    name: "LPK DUA SOBAT",
    province: "JAWA BARAT",
    vin: "1810321003",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 28 },
      { year: 2023, count: 32 },
      { year: 2024, count: 20 },
      { year: 2025, count: 15 },
    ],
    placement: 0,
  },
  {
    name: "LPK ILEADER GAKUIN CENTER",
    province: "-",
    vin: "2007320201",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 60 },
      { year: 2023, count: 60 },
      { year: 2024, count: 60 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK JI TRUST",
    province: "JAWA BARAT",
    vin: "2202327301",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 37 },
      { year: 2023, count: 63 },
      { year: 2024, count: 115 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK FUJI BIJAK PRESTASI",
    province: "JAWA BARAT",
    vin: "2412321610",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "unverified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 177 },
      { year: 2023, count: 569 },
      { year: 2024, count: 896 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK HIKARI INDONESIA",
    province: "-",
    vin: "2206321504",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 114 },
      { year: 2023, count: 153 },
      { year: 2024, count: 221 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK HAMAREN",
    province: "-",
    vin: "2003321606",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 155 },
      { year: 2023, count: 202 },
      { year: 2024, count: 115 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK KAMPUH WELDING INDONESIA",
    province: "-",
    vin: "2003357803",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 64 },
      { year: 2023, count: 43 },
      { year: 2024, count: 26 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK MAU YAKIN BISA",
    province: "DI YOGYAKARTA",
    vin: "2001347101",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 46 },
      { year: 2023, count: 95 },
      { year: 2024, count: 80 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK SAREKAH INSAN ATAMA FOUNDATION",
    province: "-",
    vin: "2005317203",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 83 },
      { year: 2023, count: 118 },
      { year: 2024, count: 143 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK BALI SORA RAHAYU",
    province: "-",
    vin: "2112510701",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 18 },
      { year: 2023, count: 39 },
      { year: 2024, count: 94 },
      { year: 2025, count: 30 },
    ],
    placement: 0,
  },
  {
    name: "BLP3-SDM YOKATTA",
    province: "-",
    vin: "2206317102",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "unverified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 78 },
      { year: 2023, count: 36 },
      { year: 2024, count: 41 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK BULAN PALAPA BALI",
    province: "BALI",
    vin: "1904510601",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 186 },
      { year: 2023, count: 158 },
      { year: 2024, count: 106 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK KIZUNA MITRA INDONESIA",
    province: "JAWA TENGAH",
    vin: "2001332204",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 0 },
      { year: 2023, count: 0 },
      { year: 2024, count: 0 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK TJOKRO BAKTI PERTIWI",
    province: "-",
    vin: "2002317201",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 9 },
      { year: 2023, count: 22 },
      { year: 2024, count: 17 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK KANZO INDONESIA",
    province: "JAWA TIMUR",
    vin: "2004350903",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 51 },
      { year: 2023, count: 68 },
      { year: 2024, count: 39 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK DWIPAHARA BALI",
    province: "-",
    vin: "2002510601",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 250 },
      { year: 2023, count: 319 },
      { year: 2024, count: 209 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK KOCHIRA BALI INDONESIA",
    province: "BALI",
    vin: "2106510401",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 35 },
      { year: 2023, count: 29 },
      { year: 2024, count: 27 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK JAYA INDONESIA BERKARYA",
    province: "JAWA BARAT",
    vin: "2103321601",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 32 },
      { year: 2023, count: 75 },
      { year: 2024, count: 98 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK KOUGAS WIJAYA NUSA",
    province: "JAWA TIMUR",
    vin: "2107351001",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 0 },
      { year: 2023, count: 0 },
      { year: 2024, count: 1 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK KOPERASI KULAK MITRA PAKUAN ARDIN JABAR",
    province: "JAWA BARAT",
    vin: "2001320402",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 45 },
      { year: 2023, count: 60 },
      { year: 2024, count: 60 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK NUSANTARA GAKKOU BANYUWANGI",
    province: "JAWA TIMUR",
    vin: "1912351001",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 75 },
      { year: 2023, count: 161 },
      { year: 2024, count: 316 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK AMANAT NEGERI SAKURA",
    province: "JAWA BARAT",
    vin: "2103320317",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 99 },
      { year: 2023, count: 150 },
      { year: 2024, count: 223 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK PURNA YUDHA PRAKASA",
    province: "JAWA BARAT",
    vin: "2108327301",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 2 },
      { year: 2023, count: 10 },
      { year: 2024, count: 0 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK MIZUNO SEMANGAT BANGSA",
    province: "-",
    vin: "1902320301",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 43 },
      { year: 2023, count: 30 },
      { year: 2024, count: 86 },
      { year: 2025, count: 143 },
    ],
    placement: 0,
  },
  {
    name: "LPK BINTANG PERMATA NUSA",
    province: "-",
    vin: "2206320903",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "unverified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 53 },
      { year: 2023, count: 20 },
      { year: 2024, count: 14 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK MUSUBU",
    province: "BALI",
    vin: "2107510402",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "unverified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 13 },
      { year: 2023, count: 10 },
      { year: 2024, count: 11 },
      { year: 2025, count: 22 },
    ],
    placement: 0,
  },
  {
    name: "LPK WIWITAN BARU SUKABUMI",
    province: "JAWA BARAT",
    vin: "9120009570071",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 10 },
      { year: 2023, count: 6 },
      { year: 2024, count: 7 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK MENTARI ASA BALI",
    province: "BALI",
    vin: "1912510401",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 10 },
      { year: 2023, count: 44 },
      { year: 2024, count: 49 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK BINTANG CEMERLANG BALI",
    province: "-",
    vin: "2011510601",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 1 },
      { year: 2023, count: 55 },
      { year: 2024, count: 114 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK DWIPAYANA CIPTA KARYA",
    province: "-",
    vin: "1912510403",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 74 },
      { year: 2023, count: 45 },
      { year: 2024, count: 110 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK FUJI ACADEMY BALI",
    province: "BALI",
    vin: "2007517103",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 42 },
      { year: 2023, count: 63 },
      { year: 2024, count: 105 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK MUDA BERDAYA NUSANTARA",
    province: "JAWA BARAT",
    vin: "2011327801",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 7 },
      { year: 2023, count: 17 },
      { year: 2024, count: 71 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK YAYASAN JABUNG MAKMUR PERKASA",
    province: "JAWA BARAT",
    vin: "1909327502",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 239 },
      { year: 2023, count: 772 },
      { year: 2024, count: 673 },
      { year: 2025, count: 512 },
    ],
    placement: 0,
  },
  {
    name: "LPK LOGIKA INTERNASIONAL",
    province: "-",
    vin: "1908527106",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 42 },
      { year: 2023, count: 33 },
      { year: 2024, count: 47 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "YAYASAN ASIAN CULTURE AND TECHNOLOGY INDONESIA",
    province: "-",
    vin: "2112510302",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 100 },
      { year: 2023, count: 80 },
      { year: 2024, count: 70 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK OOSAKA GAKKOU",
    province: "-",
    vin: "2002357101",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 0 },
      { year: 2023, count: 0 },
      { year: 2024, count: 8 },
      { year: 2025, count: 15 },
    ],
    placement: 0,
  },
  {
    name: "LPK OISCA Indonesia",
    province: "JAWA BARAT",
    vin: "320220631",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 20 },
      { year: 2023, count: 23 },
      { year: 2024, count: 31 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK ASIA TRAINING CENTER PADANG",
    province: "-",
    vin: "1906137101",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 22 },
      { year: 2023, count: 18 },
      { year: 2024, count: 31 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK TERAKOYA",
    province: "BALI",
    vin: "2010510301",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 50 },
      { year: 2023, count: 40 },
      { year: 2024, count: 30 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK MACCA INSPIRASI NUSANTARA",
    province: "SULAWESI SELATAN",
    vin: "2212737101",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "unverified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 42 },
      { year: 2023, count: 52 },
      { year: 2024, count: 72 },
      { year: 2025, count: 48 },
    ],
    placement: 0,
  },
  {
    name: "PT.CHIKARA INDONESIA  TANGGUH",
    province: "-",
    vin: "2306340404",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 0 },
      { year: 2023, count: 0 },
      { year: 2024, count: 8 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK OSIN",
    province: "JAWA BARAT",
    vin: "2008321201",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 141 },
      { year: 2023, count: 190 },
      { year: 2024, count: 90 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK KESUMA KARYA BANGSA",
    province: "JAWA TIMUR",
    vin: "2003350706",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 0 },
      { year: 2023, count: 0 },
      { year: 2024, count: 3 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK ASIA KYOEI CENTER",
    province: "-",
    vin: "2003357802",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "unverified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 0 },
      { year: 2023, count: 31 },
      { year: 2024, count: 46 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK SAKURA MEKAR",
    province: "SUMATERA BARAT",
    vin: "2012137101",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 50 },
      { year: 2023, count: 37 },
      { year: 2024, count: 13 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK TSUNAGU JAPAN INDONESIA",
    province: "SULAWESI UTARA",
    vin: "2002710201",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 372 },
      { year: 2023, count: 398 },
      { year: 2024, count: 314 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "DIPTA WIDYA SARASWATI (BALI JAPAN INTERNATIONAL COLLEGE)",
    province: "-",
    vin: "1912510301",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 0 },
      { year: 2023, count: 0 },
      { year: 2024, count: 7 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK AKSELA",
    province: "BALI",
    vin: "2103517101",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 18 },
      { year: 2023, count: 50 },
      { year: 2024, count: 17 },
      { year: 2025, count: 58 },
    ],
    placement: 0,
  },
  {
    name: "LPK YAYASAN JAPAN TECHNICAL INTERN TRAINEE SUPPORT CENTER",
    province: "JAWA BARAT",
    vin: "2008321101",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 153 },
      { year: 2023, count: 179 },
      { year: 2024, count: 109 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPKS TOYO MANDIRI",
    province: "-",
    vin: "2410337301",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "unverified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 0 },
      { year: 2023, count: 0 },
      { year: 2024, count: 0 },
      { year: 2025, count: 27 },
    ],
    placement: 0,
  },
  {
    name: "LPK KARYA SEMSESTA SEJAHTERA",
    province: "-",
    vin: "1809327503",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 54 },
      { year: 2023, count: 68 },
      { year: 2024, count: 206 },
      { year: 2025, count: 116 },
    ],
    placement: 0,
  },
  {
    name: "LPK SEIKOUNO MICHI INDONESIA",
    province: "-",
    vin: "2304367301",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 0 },
      { year: 2023, count: 0 },
      { year: 2024, count: 0 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK HIDEAKI",
    province: "-",
    vin: "2205332701",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 0 },
      { year: 2023, count: 0 },
      { year: 2024, count: 0 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK MINNA NO HIROBA",
    province: "-",
    vin: "2101320301",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "unverified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 6 },
      { year: 2023, count: 8 },
      { year: 2024, count: 0 },
      { year: 2025, count: 6 },
    ],
    placement: 0,
  },
  {
    name: "LPKS NCL MADIUN",
    province: "-",
    vin: "1905351901",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "unverified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 0 },
      { year: 2023, count: 0 },
      { year: 2024, count: 0 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPK JAPAN INTERSTUDY CENTER INDONESIA",
    province: "DI YOGYAKARTA",
    vin: "2310347101",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "unverified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 109 },
      { year: 2023, count: 86 },
      { year: 2024, count: 75 },
      { year: 2025, count: 260 },
    ],
    placement: 0,
  },
  {
    name: "LPK TATSUYA PERKASA SINGARA",
    province: "-",
    vin: "1911321504",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 0 },
      { year: 2023, count: 0 },
      { year: 2024, count: 0 },
      { year: 2025, count: 0 },
    ],
    placement: 0,
  },
  {
    name: "LPKS BALI TOSHA LOMBOK KOCHI",
    province: "-",
    vin: "1909520101",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 147 },
      { year: 2023, count: 98 },
      { year: 2024, count: 21 },
      { year: 2025, count: 27 },
    ],
    placement: 0,
  },
  {
    name: "LPK DORYOUKU",
    province: "NUSA TENGGARA BARAT",
    vin: "2101527101",
    trainingProgram: "BAHASA JEPANG",
    verificationStatus: "verified",
    realizationOfIndependentTrainings: [
      { year: 2022, count: 25 },
      { year: 2023, count: 27 },
      { year: 2024, count: 28 },
      { year: 2025, count: 15 },
    ],
    placement: 0,
  },
];
